pluginManagement {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://api.xposed.info/' }
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://api.xposed.info/' }
    }
}

rootProject.name = 'dingtalk-pin-join'
include ':app'